# Write your MySQL query statement below
SELECT
    DISTINCT L1.NUM AS CONSECUTIVENUMS

FROM
    LOGS L1

JOIN LOGS L2 ON L1.ID = L2.ID-1 AND L1.NUM = L2.NUM
JOIN LOGS L3 ON L1.ID = L3.ID-2 AND L1.NUM = L3.NUM;