# Write your MySQL query statement below
SELECT CUSTOMER_ID AS customer_id, COUNT(CUSTOMER_ID) AS count_no_trans
FROM VISITS
WHERE VISIT_ID NOT IN
(SELECT V.VISIT_ID
FROM VISITS V, TRANSACTIONS T
WHERE V.VISIT_ID = T.VISIT_ID)
GROUP BY CUSTOMER_ID;