# Write your MySQL query statement below

SELECT
    ROUND(COUNT(DISTINCT A1.PLAYER_ID) / (SELECT COUNT(DISTINCT A3.PLAYER_ID) FROM ACTIVITY A3), 2) AS FRACTION

FROM
    ACTIVITY A1

WHERE 
    DATEDIFF(EVENT_DATE, 
    (SELECT MIN(EVENT_DATE) FROM ACTIVITY A2 WHERE A1.PLAYER_ID = A2.PLAYER_ID)) = 1;
