# Write your MySQL query statement below
SELECT
    O.QUERY_NAME,
    ROUND(AVG((RATING/POSITION)), 2) AS QUALITY,
    IFNULL(ROUND((( SELECT COUNT(*) FROM QUERIES F WHERE RATING < 3 GROUP BY QUERY_NAME HAVING F.QUERY_NAME = O.QUERY_NAME) / COUNT(RATING)) * 100, 2), 0) AS POOR_QUERY_PERCENTAGE

FROM
    QUERIES O

GROUP BY
    O.QUERY_NAME

HAVING 
    O.QUERY_NAME IS NOT NULL;